build:
  version: "3.0"
spring:
  profiles:
    active: prod

accounts:
  message: "Welcome to EazyBank accounts related docker APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
